INSERT INTO final_enercare
SELECT
    DATA.DATE,
    DATA.PCC_DV360,
    DATA.PCC_CREATIVE_NAME_DV360,
    SUM(DATA.IMPRESSIONS) AS IMPRESSIONS,
    SUM(DATA.CLICKS) AS CLICKS,
    SUM(DATA.IMPRESSIONS * CPM.TOTAL_CPM) AS TOTAL_SPEND
FROM
    STD_SUMMARY_ENERCARE_REPORT DATA
LEFT JOIN (
    SELECT
        DATE,
        PCC_SITE_NAME_DV360,
        PCC_DV360,
        SUM(CREATIVE_SPEND) AS TOTAL_SPEND,
        SUM(IMPRESSIONS) AS TOTAL_IMPRESSIONS,
        CASE 
            WHEN SUM(IMPRESSIONS) = 0 THEN 0
            ELSE SUM(CREATIVE_SPEND) / SUM(IMPRESSIONS)
        END AS TOTAL_CPM
    FROM
        STD_SUMMARY_ENERCARE_REPORT
    WHERE
        LOWER(PCC_SITE_NAME_DV360) = 'dv360'
    GROUP BY
        DATE,
        PCC_SITE_NAME_DV360,
        PCC_DV360
) CPM ON 
    CPM.DATE = DATA.DATE AND 
    CPM.PCC_SITE_NAME_DV360 = DATA.PCC_SITE_NAME_DV360 AND 
    CPM.PCC_DV360 = DATA.PCC_DV360
WHERE 
    CPM.TOTAL_CPM IS NOT NULL
GROUP BY
    DATA.DATE,
    DATA.PCC_DV360,
    DATA.PCC_CREATIVE_NAME_DV360;


